
source 'https://github.com/CocoaPods/Specs.git'

workspace 'MZDesignPattern.xcworkspace'

platform :ios, '14.0'

use_frameworks!

# ignore all warnings from all dependencies
inhibit_all_warnings!

def dev_pods
  
  pod 'AFNetworking'
  pod 'SDWebImage'
  
end

def core_pods
  
  pod 'KVOController'
  pod 'MGJRouter'
  pod 'CTMediator'
  
end

def thirdparty_pods
  
  pod 'YYModel'
  
end

def ui_pods
  
end


def test_pods
  
end

target 'MZDesignPattern' do
  
  core_pods
  
end




